version: "3.8"
services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=saas-cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE CLUSTER"]
      interval: 30s
      timeout: 10s
      retries: 10
  cassandra-web:
    platform: linux/amd64
    image: ipushc/cassandra-web
    container_name: cassandra-web
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - HOST_PORT=:80
    ports:
      - "3001:80"
    depends_on:
      - cassandra
volumes:
  cassandra_data:
